### ISSUE TITLE
Invalid argument: Nan in summary histogram for: conv2/BatchNorm/moving_variance_0

### ISSUE THREAD

**Issue by IamMegatron2025** [soloice/mnist-bn#6]
hello, when I run your mnist_bn.py, it shows error:

```
Train step 0.0: entropy 0.779536366463: accuracy 0.959999978542
***** Valid step 0.0: entropy 1.93715846539: accuracy 0.620000004768 *****
2018-12-04 14:07:54.700603: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: conv2/BatchNorm/moving_variance_0
	 [[Node: conv2/BatchNorm/moving_variance_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/BatchNorm/moving_variance_0/tag, conv2/BatchNorm/AssignMovingAvg_1/read/_41)]]
2018-12-04 14:07:54.701488: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: conv2/BatchNorm/moving_variance_0
	 [[Node: conv2/BatchNorm/moving_variance_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/BatchNorm/moving_variance_0/tag, conv2/BatchNorm/AssignMovingAvg_1/read/_41)]]
2018-12-04 14:07:54.701654: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Nan in summary histogram for: conv2/BatchNorm/moving_variance_0
	 [[Node: conv2/BatchNorm/moving_variance_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/BatchNorm/moving_variance_0/tag, conv2/BatchNorm/AssignMovingAvg_1/read/_41)]]
Traceback (most recent call last):
  File "mnist_bn.py", line 188, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/xxx/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "mnist_bn.py", line 168, in main
    train()
  File "mnist_bn.py", line 105, in train
    feed_dict=train_dict)
  File "/xxx/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/xxx/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/xxx/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/xxx/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: conv2/BatchNorm/moving_variance_0
	 [[Node: conv2/BatchNorm/moving_variance_0 = HistogramSummary[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](conv2/BatchNorm/moving_variance_0/tag, conv2/BatchNorm/AssignMovingAvg_1/read/_41)]]
```

how to fix it?

**Comment by kkk324** [comment]
me too

**Comment by ruanchong** [comment]
Oops, I'll check it this weekend.

**Comment by soloice** [comment]
@IvyGongoogle Thanks for your feedback. I've replaced the slim BN with `tf.layers.batch_normalization`.
@CR-Ko I've pushed a new commit. It should work now.
